# Generated by Django 5.1.5 on 2026-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('human_resources', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('customer_support', 'Customer Support'), ('product', 'Product')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
