# Generated by Django 5.1.5 on 2026-01-08 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_department_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Reset OTP', 'verbose_name_plural': 'Password Reset OTPs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('EMPLOYEE', 'Employee')], db_index=True, max_length=20),
        ),
    ]
