# Generated by Django 5.1.5 on 2026-01-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
