# Generated by Django 5.1.5 on 2026-01-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(max_length=50)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='onboarding.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(max_length=150)),
                ('institution_name', models.CharField(max_length=150)),
                ('year_of_passing', models.IntegerField()),
                ('grade_percentage', models.CharField(max_length=20)),
                ('education_type', models.CharField(max_length=50)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='onboarding.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_company', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('experience_from', models.DateField()),
                ('experience_to', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='onboarding.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('voter_id', models.CharField(blank=True, max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=20)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='onboarding.onboarding')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('physically_handicapped', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='onboarding.onboarding')),
            ],
        ),
    ]
