# Generated by Django 5.1.5 on 2026-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_onboardingbankdetails_onboardingeducation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingidentity',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingidentity',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
