# Generated by Django 5.1.5 on 2026-01-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_onboardingidentity_uan_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onboardingdocument',
            unique_together={('onboarding', 'document_type')},
        ),
    ]
