# Generated by Django 5.1.5 on 2026-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_onboardingidentity_uan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='rejected_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
