# Generated by Django 5.1.5 on 2026-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboarding_rejected_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='rejected_section',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='rejected_sections',
            field=models.JSONField(default=list),
        ),
    ]
