# Generated by Django 5.1.5 on 2026-01-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_remove_onboarding_rejected_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='rejected_sections',
            new_name='rejected_section',
        ),
    ]
