# Generated by Django 5.1.5 on 2026-01-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_rename_rejected_section_onboarding_rejected_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='rejected_sections',
            new_name='rejected_section',
        ),
    ]
