# Generated by Django 5.1.5 on 2026-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_rename_rejected_sections_onboarding_rejected_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='rejected_section',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
