# Generated by Django 5.1.5 on 2026-01-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_alter_onboarding_rejected_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='rejected_section',
            new_name='rejected_sections',
        ),
    ]
